/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.10.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as categories from "../categories.js";
import type * as discos from "../discos.js";
import type * as messages from "../messages.js";
import type * as serviceCategories from "../serviceCategories.js";
import type * as services from "../services.js";
import type * as transactions from "../transactions.js";
import type * as userActions from "../userActions.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  categories: typeof categories;
  discos: typeof discos;
  messages: typeof messages;
  serviceCategories: typeof serviceCategories;
  services: typeof services;
  transactions: typeof transactions;
  userActions: typeof userActions;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
